apiVersion: v1
kind: Service
metadata:
  name: ccdemo-service
  labels:
    app: ccdemo-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: ccdemo-http
      targetPort: 4200
      protocol: TCP
  selector:
    name: ccdemo
