apiVersion: v1
kind: Service
metadata:
  name: ccdemo-service
  labels:
    app: ccdemo-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: ccdemo-bwebhttp
      targetPort: 8080
      protocol: TCP
  selector:
    name: ccdemo-bweb
