apiVersion: v1
kind: Service
metadata:
  name: codecampdemo-service
  labels:
    app: codecampdemo-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: codecampdemo-http
      targetPort: 8080
      protocol: TCP
  selector:
    name: codecampdemo
