kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: CodeCamp2016Demo-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: CodeCamp2016Demo
      labels:
        name: CodeCamp2016Demo
    spec:
      containers:
      - name: CodeCamp2016Demo
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: CodeCamp2016Demo-http
          containerPort: 8080
