kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ccdemo-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: ccdemo
      labels:
        name: ccdemo
    spec:
      containers:
      - name: ccdemo-sr
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0-sr
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: ccdemo-sr-http
          containerPort: 8082
      - name: ccdemo-ds
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0-ds
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: ccdemo-ds-http
          containerPort: 8081
      - name: ccdemo-web
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0-web
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: ccdemo-web-http
          containerPort: 8080

