kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ccdemo-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: ccdemo
      labels:
        name: ccdemo
    spec:
      containers:
      - name: ccdemo
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: ccdemo-http
          containerPort: 8080
