kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: codecampdemo-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: codecampdemo
      labels:
        name: codecampdemo
    spec:
      containers:
      - name: codecampdemo
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: codecampdemo-http
          containerPort: 8080
